---
- hosts: all
  become: yes
  tasks:
  - name: Update repositories cache
    apt:
      update_cache: yes
#      upgrade: dist

#  - name: Install a list of packages
#    apt:
#      name: "{{ packages }}"
#    vars:
#      packages:
#      - tmux
#      - git
#      - apache2
#      - postgresql
#      - metasploit-framework
#      - dirb
#      - sqlmap
#      - tshark
#      - john
#      - hydra
#      - aircrack-ng
#      - nikto
#      - wordlists

  - name: Add bash aliases
    lineinfile:
      dest: /root/.bashrc
      line: "alias ls='ls --color=always -lah'"
      regex: "^alias ls="
      create: yes
      
  - name: Start service apache2, if not started
    service:
      name: apache2
      state: started

  - name: Start service postgresql, if not started
    service:
      name: postgresql
      state: started
      
  - name: Initialize msfdb
    shell: "{{ item }}"
    with_items:
    - "update-rc.d postgresql enable"
    - "msfdb init"
    - "touch /usr/share/metasploit-framework/.initialized"
    args:
      creates: "/usr/share/metasploit-framework/.initialized"