# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "offensive-security/kali-linux-light"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |v|
    v.name = "Kali Light"
    v.memory = "4096"
    v.cpus = 2
    v.gui = false
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end